[server]
port = 8001

[internalAuth]
auth_username = "mez_ink"
auth_password = "Hello!@#MezInk"



[cors]
allowed_headers = ["Content-Type", "Content-Length", "Accept-Encoding", "platform"]
allowed_methods =["POST", "OPTIONS", "GET", "PUT"]
allowed_credentials = true
allowed_origin = ["http://localhost:3000"]

[database.postgres]
pg_host = "localhost"
pg_password = "root"
pg_user = "postgres"
pg_db = "student"